-- Canonical areas and their aliases are data, not hard-coded application
-- logic. Add/edit aliases here (or through an admin UI) without a deployment.
CREATE TABLE IF NOT EXISTS public.areas (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL UNIQUE,
  city text NOT NULL DEFAULT 'Bengaluru',
  latitude double precision,
  longitude double precision
);

CREATE TABLE IF NOT EXISTS public.location_aliases (
  alias_key text PRIMARY KEY,
  area_id bigint NOT NULL REFERENCES public.areas(id) ON DELETE CASCADE,
  created_at timestamptz NOT NULL DEFAULT now()
);

INSERT INTO public.areas (name)
VALUES
  ('Koramangala'),
  ('Indiranagar'),
  ('Mahadevapura'),
  ('Marathahalli'),
  ('Doddanekundi'),
  ('AECS Layout')
ON CONFLICT (name) DO NOTHING;

INSERT INTO public.location_aliases (alias_key, area_id)
SELECT seed.alias_key, a.id
FROM (
  VALUES
    ('koramangala', 'Koramangala'),
    ('kormangla', 'Koramangala'),
    ('kormanagla', 'Koramangala'),
    ('koramangla', 'Koramangala'),
    ('indiranagar', 'Indiranagar'),
    ('indranagar', 'Indiranagar'),
    ('mahadevapura', 'Mahadevapura'),
    ('mahadev pura', 'Mahadevapura'),
    ('marathahalli', 'Marathahalli'),
    ('marathalli', 'Marathahalli'),
    ('doddanekundi', 'Doddanekundi'),
    ('aecs layout', 'AECS Layout')
) AS seed(alias_key, area_name)
JOIN public.areas AS a ON a.name = seed.area_name
ON CONFLICT (alias_key) DO UPDATE SET area_id = EXCLUDED.area_id;

-- Repair legacy rows from the same alias reference data. The area list keeps
-- its original order and leaves unknown locations untouched.
UPDATE public.listings AS l
SET location = ARRAY(
  SELECT COALESCE(a.name, item.area)
  FROM unnest(l.location) WITH ORDINALITY AS item(area, position)
  LEFT JOIN public.location_aliases AS alias
    ON alias.alias_key = lower(trim(regexp_replace(
      regexp_replace(item.area, '[^[:alnum:]]+', ' ', 'g'),
      '[[:space:]]+',
      ' ',
      'g'
    )))
  LEFT JOIN public.areas AS a ON a.id = alias.area_id
  ORDER BY item.position
);
