-- Canonical locations used by the user-facing autocomplete flow.
CREATE TABLE IF NOT EXISTS public.locations (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  city text NOT NULL,
  latitude double precision,
  longitude double precision,
  UNIQUE (name, city)
);

-- Starter data keeps this migration independent of the legacy `areas` table.
-- Add more canonical locations here or through an admin workflow later.
INSERT INTO public.locations (name, city, latitude, longitude)
VALUES
  ('Koramangala', 'Bengaluru', 12.9352, 77.6245),
  ('Koramangala 1st Block', 'Bengaluru', 12.9347, 77.6247),
  ('Koramangala 5th Block', 'Bengaluru', 12.9349, 77.6131),
  ('Indiranagar', 'Bengaluru', 12.9784, 77.6408),
  ('Mahadevapura', 'Bengaluru', 12.9916, 77.7041),
  ('Marathahalli', 'Bengaluru', 12.9591, 77.6974)
ON CONFLICT (name, city) DO NOTHING;

ALTER TABLE public.listings
  ADD COLUMN IF NOT EXISTS location_id bigint REFERENCES public.locations(id);

CREATE INDEX IF NOT EXISTS locations_name_search_idx
  ON public.locations (lower(name), lower(city));

CREATE INDEX IF NOT EXISTS listings_location_id_idx
  ON public.listings (location_id);

NOTIFY pgrst, 'reload schema';
